# Generated by Django 3.0.4 on 2020-04-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('information', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(upload_to='uploads/teams/')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Info', serialize=False, to='football.Team')),
            ],
            options={
                'verbose_name': 'Team Information',
            },
        ),
    ]
