# Generated by Django 3.0.4 on 2020-04-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(default='no-image.png', upload_to='uploads/leagues/')),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to='uploads/teams/'),
        ),
        migrations.AddField(
            model_name='team',
            name='information',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='TeamInfo',
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='League', to='football.League'),
        ),
    ]
