# Generated by Django 3.0.4 on 2020-04-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20200405_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='information',
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='League', to='football.League'),
        ),
    ]
