# Generated by Django 3.0.5 on 2020-04-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('table', 'Table'), ('4x4', 'GRID 8 Teams'), ('8x8', 'GRID 16 Teams')], default='table', max_length=5),
        ),
    ]
