# Generated by Django 3.0.5 on 2020-04-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20200411_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
