# Generated by Django 3.0.5 on 2020-04-11 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20200411_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
