# Generated by Django 3.0.5 on 2020-04-11 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_tournament_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
