# Generated by Django 3.0.5 on 2020-04-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Team_1', to='football.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Team_2', to='football.Team'),
        ),
    ]
