# Generated by Django 3.0.5 on 2020-05-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_auto_20200428_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.SmallIntegerField(default=0)),
                ('won', models.SmallIntegerField(default=0)),
                ('drawn', models.SmallIntegerField(default=0)),
                ('lost', models.SmallIntegerField(default=0)),
                ('goal_scored', models.SmallIntegerField(default=0)),
                ('goal_conceded', models.SmallIntegerField(default=0)),
                ('points', models.SmallIntegerField(default=0)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='football.Team')),
                ('tournament', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='football.Tournament')),
            ],
            options={
                'verbose_name': 'Team Info',
                'verbose_name_plural': 'Teams Info',
            },
        ),
    ]
