# Generated by Django 3.0.5 on 2020-05-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_tournamentteaminfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentteaminfo',
            old_name='team_id',
            new_name='team',
        ),
    ]
